// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: api/vault.proto

package vaultpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SealRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SealRequest) Reset() {
	*x = SealRequest{}
	mi := &file_api_vault_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SealRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SealRequest) ProtoMessage() {}

func (x *SealRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_vault_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SealRequest.ProtoReflect.Descriptor instead.
func (*SealRequest) Descriptor() ([]byte, []int) {
	return file_api_vault_proto_rawDescGZIP(), []int{0}
}

type SealResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SealResponse) Reset() {
	*x = SealResponse{}
	mi := &file_api_vault_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SealResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SealResponse) ProtoMessage() {}

func (x *SealResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_vault_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SealResponse.ProtoReflect.Descriptor instead.
func (*SealResponse) Descriptor() ([]byte, []int) {
	return file_api_vault_proto_rawDescGZIP(), []int{1}
}

func (x *SealResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UnsealRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []string               `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsealRequest) Reset() {
	*x = UnsealRequest{}
	mi := &file_api_vault_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsealRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsealRequest) ProtoMessage() {}

func (x *UnsealRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_vault_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsealRequest.ProtoReflect.Descriptor instead.
func (*UnsealRequest) Descriptor() ([]byte, []int) {
	return file_api_vault_proto_rawDescGZIP(), []int{2}
}

func (x *UnsealRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type UnsealResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsealResponse) Reset() {
	*x = UnsealResponse{}
	mi := &file_api_vault_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsealResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsealResponse) ProtoMessage() {}

func (x *UnsealResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_vault_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsealResponse.ProtoReflect.Descriptor instead.
func (*UnsealResponse) Descriptor() ([]byte, []int) {
	return file_api_vault_proto_rawDescGZIP(), []int{3}
}

func (x *UnsealResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_api_vault_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_vault_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_api_vault_proto_rawDescGZIP(), []int{4}
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_api_vault_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_vault_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_api_vault_proto_rawDescGZIP(), []int{5}
}

func (x *StatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StatusResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_api_vault_proto protoreflect.FileDescriptor

const file_api_vault_proto_rawDesc = "" +
	"\n" +
	"\x0fapi/vault.proto\x12\x05vault\"\r\n" +
	"\vSealRequest\"$\n" +
	"\fSealResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"#\n" +
	"\rUnsealRequest\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\tR\x04keys\"&\n" +
	"\x0eUnsealResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"\x0f\n" +
	"\rStatusRequest\">\n" +
	"\x0eStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xad\x01\n" +
	"\fVaultService\x12/\n" +
	"\x04Seal\x12\x12.vault.SealRequest\x1a\x13.vault.SealResponse\x125\n" +
	"\x06Unseal\x12\x14.vault.UnsealRequest\x1a\x15.vault.UnsealResponse\x125\n" +
	"\x06Status\x12\x14.vault.StatusRequest\x1a\x15.vault.StatusResponseB)Z'github.com/heimweh/passwort/api/vaultpbb\x06proto3"

var (
	file_api_vault_proto_rawDescOnce sync.Once
	file_api_vault_proto_rawDescData []byte
)

func file_api_vault_proto_rawDescGZIP() []byte {
	file_api_vault_proto_rawDescOnce.Do(func() {
		file_api_vault_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_vault_proto_rawDesc), len(file_api_vault_proto_rawDesc)))
	})
	return file_api_vault_proto_rawDescData
}

var file_api_vault_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_vault_proto_goTypes = []any{
	(*SealRequest)(nil),    // 0: vault.SealRequest
	(*SealResponse)(nil),   // 1: vault.SealResponse
	(*UnsealRequest)(nil),  // 2: vault.UnsealRequest
	(*UnsealResponse)(nil), // 3: vault.UnsealResponse
	(*StatusRequest)(nil),  // 4: vault.StatusRequest
	(*StatusResponse)(nil), // 5: vault.StatusResponse
}
var file_api_vault_proto_depIdxs = []int32{
	0, // 0: vault.VaultService.Seal:input_type -> vault.SealRequest
	2, // 1: vault.VaultService.Unseal:input_type -> vault.UnsealRequest
	4, // 2: vault.VaultService.Status:input_type -> vault.StatusRequest
	1, // 3: vault.VaultService.Seal:output_type -> vault.SealResponse
	3, // 4: vault.VaultService.Unseal:output_type -> vault.UnsealResponse
	5, // 5: vault.VaultService.Status:output_type -> vault.StatusResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_vault_proto_init() }
func file_api_vault_proto_init() {
	if File_api_vault_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_vault_proto_rawDesc), len(file_api_vault_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_vault_proto_goTypes,
		DependencyIndexes: file_api_vault_proto_depIdxs,
		MessageInfos:      file_api_vault_proto_msgTypes,
	}.Build()
	File_api_vault_proto = out.File
	file_api_vault_proto_goTypes = nil
	file_api_vault_proto_depIdxs = nil
}
